### ISSUE TITLE
有木有docker想直接开呢

### ISSUE THREAD

**Issue by tvvocold** [lcjnil/hole#2]

**Comment by lcjnil** [comment]
太简单没有配置docker的必要...
只需要安装好mongo nodejs 以及nodejs的bower应该就可以直接run起来

**Comment by lcjnil** [comment]
如果有什么问题只需要联系我就可以了，不过这个说实话前端技术实现太老了，我甚至连ajax都没用（因为我不喜欢jQuery这种操控dom的框架）

如果可能，会考虑加入websocket。
